// SPDX-FileCopyrightText: 2026 KIM Hyunjae
// SPDX-License-Identifier: AGPL-3.0-or-later

import { mkdir, readFile, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const bindingCount = 16;
const bindingFields = [
  { name: "Enabled", type: "Bool", defaultValue: "false" },
  { name: "Name", type: "String", defaultValue: "" },
  { name: "DesktopEntryId", type: "String", defaultValue: "" },
  { name: "Shortcut", type: "String", defaultValue: "" },
];
const packageDir = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  "..",
);
const buildCodeFiles = [
  path.join(packageDir, "build", "src", "core.js"),
  path.join(packageDir, "build", "src", "main.js"),
];
const distRoot = path.join(packageDir, "dist", "kwin-run-or-raise");
const distCodeDir = path.join(distRoot, "contents", "code");

const metadata = {
  KPackageStructure: "KWin/Script",
  KPlugin: {
    Authors: [
      {
        Name: "KIM Hyunjae",
      },
    ],
    Category: "Window Management",
    Description: "Run or raise configured applications with global shortcuts.",
    Icon: "preferences-system-windows",
    Id: "io.github.hnjae.kwin-run-or-raise",
    License: "AGPL-3.0-or-later",
    Name: "Run or Raise",
    Version: "0.1.0",
  },
  "X-Plasma-API": "javascript",
  "X-Plasma-MainScript": "code/main.js",
  "X-KDE-ConfigModule": "kwin/effects/configs/kcm_kwin4_genericscripted",
};

function slotName(slot) {
  return `Binding${String(slot).padStart(2, "0")}`;
}

function generatedFileComment(indent = "") {
  const spdxPrefix = "SPDX";

  return [
    `${indent}${spdxPrefix}-FileCopyrightText: 2026 KIM Hyunjae`,
    `${indent}${spdxPrefix}-License-Identifier: AGPL-3.0-or-later`,
    `${indent}Generated by scripts/build-package.mjs.`,
  ].join("\n");
}

function configEntries() {
  const entries = [];

  for (let slot = 1; slot <= bindingCount; slot += 1) {
    const name = slotName(slot);

    for (const field of bindingFields) {
      entries.push(
        [
          `        <entry name="${name}${field.name}" type="${field.type}">`,
          `            <default>${field.defaultValue}</default>`,
          "        </entry>",
        ].join("\n"),
      );
    }
  }

  return entries.join("\n");
}

function generateMainConfig() {
  return `${[
    '<?xml version="1.0" encoding="UTF-8"?>',
    "<!--",
    generatedFileComment(),
    "-->",
    '<kcfg xmlns="http://www.kde.org/standards/kcfg/1.0"',
    '      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"',
    '      xsi:schemaLocation="http://www.kde.org/standards/kcfg/1.0 https://www.kde.org/standards/kcfg/1.0/kcfg.xsd">',
    '    <kcfgfile name=""/>',
    '    <group name="">',
    configEntries(),
    "    </group>",
    "</kcfg>",
  ].join("\n")}\n`;
}

function uiCell(row, column, body) {
  return [
    `                            <item row="${row}" column="${column}">`,
    body,
    "                            </item>",
  ].join("\n");
}

function label(name, text) {
  return [
    `                                <widget class="QLabel" name="${name}">`,
    '                                    <property name="text">',
    `                                        <string>${text}</string>`,
    "                                    </property>",
    "                                </widget>",
  ].join("\n");
}

function widget(className, name) {
  return `                                <widget class="${className}" name="${name}"/>`;
}

function configUiRows() {
  const rows = [
    uiCell(0, 0, label("enabledLabel", "Enabled")),
    uiCell(0, 1, label("slotLabel", "Slot")),
    uiCell(0, 2, label("nameLabel", "Name")),
    uiCell(0, 3, label("desktopEntryIdLabel", "Desktop Entry ID")),
    uiCell(0, 4, label("shortcutLabel", "Default Shortcut")),
  ];

  for (let slot = 1; slot <= bindingCount; slot += 1) {
    const name = slotName(slot);
    const row = slot;
    const labelName = `${name.slice(0, 1).toLowerCase()}${name.slice(1)}Label`;

    rows.push(
      uiCell(row, 0, widget("QCheckBox", `kcfg_${name}Enabled`)),
      uiCell(row, 1, label(labelName, String(slot))),
      uiCell(row, 2, widget("QLineEdit", `kcfg_${name}Name`)),
      uiCell(row, 3, widget("QLineEdit", `kcfg_${name}DesktopEntryId`)),
      uiCell(row, 4, widget("QLineEdit", `kcfg_${name}Shortcut`)),
    );
  }

  return rows.join("\n");
}

function generateConfigUi() {
  return `${[
    '<?xml version="1.0" encoding="UTF-8"?>',
    "<!--",
    generatedFileComment(),
    "-->",
    '<ui version="4.0">',
    "    <class>RunOrRaiseConfig</class>",
    '    <widget class="QWidget" name="RunOrRaiseConfig">',
    '        <layout class="QVBoxLayout" name="verticalLayout">',
    "            <item>",
    '                <widget class="QScrollArea" name="scrollArea">',
    '                    <property name="widgetResizable">',
    "                        <bool>true</bool>",
    "                    </property>",
    '                    <widget class="QWidget" name="scrollAreaWidgetContents">',
    '                        <property name="geometry">',
    "                            <rect>",
    "                                <x>0</x>",
    "                                <y>0</y>",
    "                                <width>760</width>",
    "                                <height>620</height>",
    "                            </rect>",
    "                        </property>",
    '                        <layout class="QGridLayout" name="bindingsLayout">',
    configUiRows(),
    "                        </layout>",
    "                    </widget>",
    "                </widget>",
    "            </item>",
    "        </layout>",
    "    </widget>",
    "    <resources/>",
    "    <connections/>",
    "</ui>",
  ].join("\n")}\n`;
}

await rm(distRoot, { force: true, recursive: true });
await mkdir(distCodeDir, { recursive: true });
const scriptParts = await Promise.all(
  buildCodeFiles.map((file) => readFile(file, "utf8")),
);
await writeFile(
  path.join(distCodeDir, "main.js"),
  `${scriptParts.join("\n")}\n`,
);
await mkdir(path.join(distRoot, "contents", "config"), { recursive: true });
await mkdir(path.join(distRoot, "contents", "ui"), { recursive: true });
await writeFile(
  path.join(distRoot, "contents", "config", "main.xml"),
  generateMainConfig(),
);
await writeFile(
  path.join(distRoot, "contents", "ui", "config.ui"),
  generateConfigUi(),
);
await writeFile(
  path.join(distRoot, "metadata.json"),
  `${JSON.stringify(metadata, null, 2)}\n`,
);
