// SPDX-FileCopyrightText: 2026 KIM Hyunjae
// SPDX-License-Identifier: AGPL-3.0-or-later

import { mkdir, readFile, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import vm from "node:vm";

const packageDir = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  "..",
);
const buildCoreFile = path.join(packageDir, "build", "src", "core.js");
const buildCodeFiles = [
  buildCoreFile,
  path.join(packageDir, "build", "src", "window-matching.js"),
  path.join(packageDir, "build", "src", "action-planning.js"),
  path.join(packageDir, "build", "src", "controller.js"),
  path.join(packageDir, "build", "src", "bindings.js"),
  path.join(packageDir, "build", "src", "runtime.js"),
  path.join(packageDir, "build", "src", "main.js"),
];
const distRoot = path.join(packageDir, "dist", "kwin-run-or-raise");
const distCodeDir = path.join(distRoot, "contents", "code");

const metadata = {
  KPackageStructure: "KWin/Script",
  KPlugin: {
    Authors: [
      {
        Name: "KIM Hyunjae",
      },
    ],
    Category: "Window Management",
    Description: "Run or raise configured applications with global shortcuts.",
    Icon: "preferences-system-windows",
    Id: "io.github.hnjae.kwin-run-or-raise",
    License: "AGPL-3.0-or-later",
    Name: "Run or Raise",
    Version: "0.1.0",
  },
  "X-Plasma-API": "javascript",
  "X-Plasma-MainScript": "code/main.js",
  "X-KDE-ConfigModule": "kwin/effects/configs/kcm_kwin4_genericscripted",
};

function generatedFileComment(indent = "") {
  const spdxPrefix = "SPDX";

  return [
    `${indent}${spdxPrefix}-FileCopyrightText: 2026 KIM Hyunjae`,
    `${indent}${spdxPrefix}-License-Identifier: AGPL-3.0-or-later`,
    `${indent}Generated by scripts/build-package.mjs.`,
  ].join("\n");
}

function loadBindingSchema(coreSource) {
  const bindingSchema = vm.runInNewContext(
    `${coreSource}
({
  fields: RunOrRaise.bindingConfigFields,
  slots: RunOrRaise.bindingSlotNames(),
});`,
    {},
  );

  if (
    typeof bindingSchema !== "object" ||
    bindingSchema === null ||
    !Array.isArray(bindingSchema.slots) ||
    bindingSchema.slots.length === 0 ||
    bindingSchema.slots.some((slot) => typeof slot !== "string" || slot === "")
  ) {
    throw new Error(
      "Failed to load binding slot schema from build/src/core.js",
    );
  }

  if (
    !Array.isArray(bindingSchema.fields) ||
    bindingSchema.fields.length === 0 ||
    bindingSchema.fields.some(
      (field) =>
        typeof field !== "object" ||
        field === null ||
        typeof field.name !== "string" ||
        typeof field.label !== "string" ||
        typeof field.valueType !== "string" ||
        typeof field.widgetClass !== "string" ||
        !["boolean", "string"].includes(typeof field.defaultValue),
    )
  ) {
    throw new Error(
      "Failed to load binding field schema from build/src/core.js",
    );
  }

  return bindingSchema;
}

function configEntries(bindingSchema) {
  const entries = [];

  for (const name of bindingSchema.slots) {
    for (const field of bindingSchema.fields) {
      entries.push(
        [
          `        <entry name="${name}${field.name}" type="${field.valueType}">`,
          `            <default>${field.defaultValue}</default>`,
          "        </entry>",
        ].join("\n"),
      );
    }
  }

  return entries.join("\n");
}

function generateMainConfig(bindingSchema) {
  return `${[
    '<?xml version="1.0" encoding="UTF-8"?>',
    "<!--",
    generatedFileComment(),
    "-->",
    '<kcfg xmlns="http://www.kde.org/standards/kcfg/1.0"',
    '      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"',
    '      xsi:schemaLocation="http://www.kde.org/standards/kcfg/1.0 https://www.kde.org/standards/kcfg/1.0/kcfg.xsd">',
    '    <kcfgfile name=""/>',
    '    <group name="">',
    configEntries(bindingSchema),
    "    </group>",
    "</kcfg>",
  ].join("\n")}\n`;
}

function uiCell(row, column, body) {
  return [
    `                            <item row="${row}" column="${column}">`,
    body,
    "                            </item>",
  ].join("\n");
}

function label(name, text) {
  return [
    `                                <widget class="QLabel" name="${name}">`,
    '                                    <property name="text">',
    `                                        <string>${text}</string>`,
    "                                    </property>",
    "                                </widget>",
  ].join("\n");
}

function widget(className, name) {
  return `                                <widget class="${className}" name="${name}"/>`;
}

function fieldColumn(index) {
  return index === 0 ? 0 : index + 1;
}

function configUiRows(bindingSchema) {
  const rows = [uiCell(0, 1, label("slotLabel", "Slot"))];

  for (let index = 0; index < bindingSchema.fields.length; index += 1) {
    const field = bindingSchema.fields[index];
    const labelName = `${field.name.slice(0, 1).toLowerCase()}${field.name.slice(
      1,
    )}Label`;

    rows.push(uiCell(0, fieldColumn(index), label(labelName, field.label)));
  }

  for (let index = 0; index < bindingSchema.slots.length; index += 1) {
    const name = bindingSchema.slots[index];
    const row = index + 1;
    const slotLabelName = `${name.slice(0, 1).toLowerCase()}${name.slice(
      1,
    )}Label`;

    rows.push(uiCell(row, 1, label(slotLabelName, String(row))));

    for (
      let fieldIndex = 0;
      fieldIndex < bindingSchema.fields.length;
      fieldIndex += 1
    ) {
      const field = bindingSchema.fields[fieldIndex];

      rows.push(
        uiCell(
          row,
          fieldColumn(fieldIndex),
          widget(field.widgetClass, `kcfg_${name}${field.name}`),
        ),
      );
    }
  }

  return rows.join("\n");
}

function generateConfigUi(bindingSchema) {
  return `${[
    '<?xml version="1.0" encoding="UTF-8"?>',
    "<!--",
    generatedFileComment(),
    "-->",
    '<ui version="4.0">',
    "    <class>RunOrRaiseConfig</class>",
    '    <widget class="QWidget" name="RunOrRaiseConfig">',
    '        <layout class="QVBoxLayout" name="verticalLayout">',
    "            <item>",
    '                <widget class="QScrollArea" name="scrollArea">',
    '                    <property name="widgetResizable">',
    "                        <bool>true</bool>",
    "                    </property>",
    '                    <widget class="QWidget" name="scrollAreaWidgetContents">',
    '                        <property name="geometry">',
    "                            <rect>",
    "                                <x>0</x>",
    "                                <y>0</y>",
    "                                <width>760</width>",
    "                                <height>620</height>",
    "                            </rect>",
    "                        </property>",
    '                        <layout class="QGridLayout" name="bindingsLayout">',
    configUiRows(bindingSchema),
    "                        </layout>",
    "                    </widget>",
    "                </widget>",
    "            </item>",
    "        </layout>",
    "    </widget>",
    "    <resources/>",
    "    <connections/>",
    "</ui>",
  ].join("\n")}\n`;
}

await rm(distRoot, { force: true, recursive: true });
await mkdir(distCodeDir, { recursive: true });
const scriptParts = await Promise.all(
  buildCodeFiles.map((file) => readFile(file, "utf8")),
);
const bindingSchema = loadBindingSchema(scriptParts[0]);
await writeFile(
  path.join(distCodeDir, "main.js"),
  `${scriptParts.join("\n")}\n`,
);
await mkdir(path.join(distRoot, "contents", "config"), { recursive: true });
await mkdir(path.join(distRoot, "contents", "ui"), { recursive: true });
await writeFile(
  path.join(distRoot, "contents", "config", "main.xml"),
  generateMainConfig(bindingSchema),
);
await writeFile(
  path.join(distRoot, "contents", "ui", "config.ui"),
  generateConfigUi(bindingSchema),
);
await writeFile(
  path.join(distRoot, "metadata.json"),
  `${JSON.stringify(metadata, null, 2)}\n`,
);
