version = 1
SPDX-PackageName = "kde-plasma-extensions"

[[annotations]]
path = [
  "**/.clang-tidy",
  "**/.editorconfig",
  "**/.envrc",
  "**/.gitignore",
  "**/biome.json",
  "**/rumdl.toml",
  "**/taplo.toml",
  "**/typos.toml",
  "**/yamlfmt.yaml",
  "**/README.*",
  "**/*.md",
  "**/flake.lock",
  "**/justfile",
  "**/kpackage.json",
  "**/metadata.json",
  "**/package-lock.json",
  "**/package.json",
  "**/statix.toml",
  "**/tsconfig.json",
  "cog.toml",
  "packages/*/src/**/*.qmltypes",
  "packages/*/src/**/qmldir",
  "packages/*/src/**/qmldir.in",
]
precedence = "closest"
SPDX-FileCopyrightText = "2026 KIM Hyunjae"
SPDX-License-Identifier = "AGPL-3.0-or-later"
